environment: development
port: 8080
company:
  wechat:
    mchId: mch-id
    mchCertNo: mch-cert-no
    mchAPIv3Key: mch-api-v3-key
    mchPrivateKey: mch-priv-key
  alipay:
    privateKey:   my-priv-key
    alipayPublicKey: alipay-pub-key
  cmb:
    appId: cmb-appid
    appInternalID: 3
    apiServer: "http://cdctest.cmburl.cn/cdcserver/api/v2"
    userId: xxx
    sm4Key: xxx
    sm2PrivateKey: xxx
    accNbr: xxx
    bbkNbr: xxx
    unitManagerBusmod: xxx
apps:
  cns:
    appIdAlipay: appid-alipay
    appIdWechat: appid-wechat
    appSecretHash: cns-app-secret
    appInternalID: 1
  rainbow:
    appId: rainbow-appid
    appSecret: rainbow-app-secret
    appInternalID: 2
inNotify: # 接受 微信官方支付服务 的通知
  wechat:
    payNotifyUrlBase: http://127.0.0.1:8080
    refundNotifyUrlBase: http://127.0.0.1:8080
    enable: true
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: conflux_pay_test
log:
  level: trace # trace,debug,info,warn,error,fatal,panic
  folder: /Users/dayong/myspace/mywork/conflux-pay/.log